### ISSUE TITLE
存在无法显示二维码的情况

### ISSUE THREAD

**Issue by xyy94813** [l-ll/qrcode-vue#3]
由于未知原因，存在无法显示二维码的情况。

然后，刚在 browserstack，使用 iphone 6s，ios 9 ，safari 的配置进行模拟复现。

然后有一定几率复现无法显示二维码的情况，该情况下查看控制面板：
`Cross-origin image load denied by Cross-Origin Resource Sharing policy.`

**Comment by xyy94813** [comment]
今天又试了一下，如果传入的 logo，为 base 64 形式（被 file-loader 压缩），在 ios 9， safari 9？ 中就会触发
跨域的问题。高版本的 safari 则不会出现这个问题

**Comment by qingyl** [comment]
建议logo进行改进判断，非加logo的时候也能出二维码

**Comment by l-ll** [comment]
@qingyl  已修复
